# Comparativo Técnico – AWS Step Functions: Standard Workflow vs. Express Workflow

| **Categoria**                          | **Standard Workflow**                                                                                                                                                        | **Express Workflow (síncrono e assíncrono)**                                                                                                                                                               |
| -------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Duração máxima da execução**         | Até **1 ano** por execução, adequado para processos de longa duração e orquestrações complexas.                                                                              | Até **5 minutos** por execução, otimizado para workloads de baixa latência e curta duração.                                                                                                                |
| **Taxa inicial de execução**           | Sujeita a limites de **throughput inicial** definidos por cotas de API. Pode ser expandido via solicitação ao suporte AWS.                                                   | Também sujeita a cotas de **throughput inicial**, porém otimizadas para workloads de alta taxa de requisições simultâneas.                                                                                 |
| **Taxa de transições de estado**       | Limitada por cotas de transição de estado. Cada mudança de estado consome quota.                                                                                             | **Ilimitada** – sem restrições explícitas na taxa de transições de estado.                                                                                                                                 |
| **Modelo de cobrança**                 | Baseado em número de **transições de estado** realizadas dentro da execução. Ideal para fluxos esparsos ou de longa duração.                                                 | Baseado em **número de execuções** e na **duração em milissegundos** de cada execução. Mais econômico em cenários de alto volume e curta duração.                                                          |
| **Histórico de execução**              | Persistência detalhada: todas as execuções podem ser listadas, inspecionadas e depuradas via **Step Functions APIs**, Console AWS e **CloudWatch Logs** (quando habilitado). | Histórico limitado ao período de execução (máx. 5 min). Logs detalhados apenas via **CloudWatch Logs** ou inspeção direta no console. Não há persistência estendida.                                       |
| **Semântica de execução**              | **Exactly-once** workflow: garante execução única e idempotente.                                                                                                             | - **Asynchronous Express:** **At-least-once** (execução pode ocorrer mais de uma vez em cenários de falha).<br> - **Synchronous Express:** resposta imediata ao chamador, sem garantias de execução única. |
| **Integrações de serviço**             | Suporta **todas as integrações nativas** (Lambda, DynamoDB, SQS, SNS, ECS, etc.) e padrões avançados: **Job-run (.sync)** e **Callback (waitForTaskToken)**.                 | Suporta integrações de serviço, mas **não suporta** os padrões **Job-run (.sync)** e **Callback (waitForTaskToken)**.                                                                                      |
| **Mapa distribuído (Distributed Map)** | **Totalmente compatível**, possibilitando processamento paralelo em larga escala.                                                                                            | **Não compatível**.                                                                                                                                                                                        |
| **Atividades (Activities)**            | **Suportadas**, permitindo workers externos interagirem com o fluxo.                                                                                                         | **Não suportadas**.                                                                                                                                                                                        |
